### ISSUE TITLE
Unknown provider: csrfProvider

### ISSUE THREAD

**Issue by tnabil** [aditzel/spring-security-csrf-token-interceptor#11]
Hi,

I followed the readme to configure the module but I'm getting an "Unknown provider: csrfProvider" error. I looked at the source and it doesn't seem to be creating any providers. Am I missing anything?

**Comment by tnabil** [comment]
I realized this is a duplicate of issue #10

**Comment by karthilxg** [comment]
@tnabil @aditzel 
> Created a new tag 0.2.0 and published it

https://github.com/karthilxg/spring-security-csrf-token-interceptor/releases
