### ISSUE TITLE
Interceptor forces url to "/"

### ISSUE THREAD

**Issue by rjmveloso** [aditzel/spring-security-csrf-token-interceptor#6]
The intercepter should allow to configure the XMLHttpRequest url in order to make it flexible to use.
I'm currently using an EAR project with two WARs inside, and only one is being developed with Angular JS and Spring Security and I can't set the url for the correct context.

**Comment by karthilxg** [comment]
@rjmveloso Added feature for configuring the XMLHttpRequest URL and few other options. Let me know if that helps.

https://github.com/aditzel/spring-security-csrf-token-interceptor/pull/7

**Comment by karthilxg** [comment]
@aditzel This issue can be closed

**Comment by rjmveloso** [comment]
It does the job. Thanks for the support..

**Comment by karthilxg** [comment]
@rjmveloso Good to hear :+1:

**Comment by karthilxg** [comment]
@aditzel You can close this issue
