### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by pierrecheron** [aditzel/spring-security-csrf-token-interceptor#8]
Hello,

I'm using your AngularJS interceptor and I got the following warning message when I debug in the browser (chrome).
"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.       It refers to the line 29 in 'src/spring-security-csrf-token-interceptor.js' : 
xhr.open('head', '/', false);

If I change false to true, the warning message disappears. I don't really understand it. 

Do you know something about that ?

many thanks

**Comment by karthilxg** [comment]
@pierrecheron The warning message is due to an XMLHttpRequest request within the main thread with the async flag set to false.

https://xhr.spec.whatwg.org/#synchronous-flag

>Synchronous XMLHttpRequest outside of workers is in the process of being removed from the web platform as it has detrimental effects to the end user's experience. (This is a long process that takes many years.) Developers must not pass false for the async argument when the JavaScript global environment is a document environment. User agents are strongly encouraged to warn about such usage in developer tools and may experiment with throwing an InvalidAccessError exception when it occurs.
The future direction is to only allow XMLHttpRequests in worker threads. The message is intended to be a warning to that effect.

**Comment by Codermar** [comment]
The warning can be suppressed by adding true to: (line 84)
xhr.open(this.settings.csrfHttpType, this.settings.url, true);
Is there any harm in doing that? 
Also, this could be added to the configuration if that's the case so we can turn it true or false
xhr.open(this.settings.csrfHttpType, this.settings.url, this.settings.asyncFlag);

Just starting to use the interceptor. Thanks for your wonderful work!

**Comment by TrueDub** [comment]
@Codermar I tried making that change, and it meant the token did not get read, therefore the interceptor stopped working. The fix might be more complicated than you suggest.
